#
# Experimental Travis CI.
#
# Linux ARM64 target is pinned on the oldest distribution available on Travis,
# thus matching a generic ARM64 Linux build.

language: shell

git:
  depth: false

jobs:
  include:
    # Ubuntu Server 16.04 on ARM64
    - os: linux
      dist: xenial
      arch: arm64

    # macOS 10.13
    - os: osx
      osx_image: xcode10.1

install:
  - |
    case $TRAVIS_OS_NAME in
      osx)
        # Some Homebrew libs pollute the build.
        sudo chmod a-r /usr/local/opt/libffi/lib/libffi.6.dylib
        ;;
    esac

before_script:
  - ./brink.sh detect_os

script:
  - ./chevah_build build && ./chevah_build test && ./chevah_build test_compat

notifications:
  email:
    - dumol@gmx.co.uk
