#!/usr/bin/env bash
#
# Chevah Build Script for libffi.
#
# For now it is supported only on AIX, Solaris and ArchLinux.
#
# Import shared code.
. ./functions.sh


chevahbs_configure() {
    # We want only static build so that we don't have to mess with LIBPATH.
    execute ./configure --prefix="" --disable-shared --enable-static
}


chevahbs_compile() {
    execute $MAKE
}


chevahbs_install() {
    execute $MAKE install DESTDIR=$INSTALL_FOLDER

    # libffi installs its headers in $PREFIX/lib/libffi-$VERSION/include,
    # instead of $PREFIX/include, so we copy them manually to the default
    # location.
    execute mkdir -p $INSTALL_FOLDER/include
    execute cp $INSTALL_FOLDER/lib/libffi-*/include/* $INSTALL_FOLDER/include
}


select_chevahbs_command $@
