#!/usr/bin/env bash
#
# Chevah Build Script for libffi.
#
# For now it is supported only on AIX, Solaris and ArchLinux.
#
# Import shared code.
. ./functions.sh


chevahbs_configure() {
    case $OS in
        hpux*|solaris10u3)
            # On some exotic platforms libffi only compiles with GCC.
            CC="gcc"
            CXX="g++"
            MAKE="gmake"
            unset CFLAGS
            ;;
    esac
    # We want only static build so that we don't have to mess with LIBPATH.
    execute ./configure --prefix="" --disable-shared --enable-static
}


chevahbs_compile() {
    execute $MAKE
}


chevahbs_install() {
    install_folder=$1

    # Installing fails on some OS'es.
    # Following workarounds should cover all 32/64bit cases for all arches.
    case $OS in
        aix*)
            execute ln -s ../install-sh powerpc-ibm-aix"$(oslevel)"/install-sh
            ;;
        solaris10*)
            case $ARCH in
                sparc*)
                    execute ln -s ../install-sh sparc-sun-solaris2.10/install-sh
                    ;;
                *)
                    execute ln -s ../install-sh i386-pc-solaris2.10/install-sh
                    ;;
            esac
            ;;
        hpux1131)
            execute ln -s ../install-sh "$(uname -m)"-hp-hpux11.31/install-sh
            ;;
    esac

    execute $MAKE install DESTDIR=$INSTALL_FOLDER

    if [ ! -d $INSTALL_FOLDER/include ]; then
        # 3.2.1 installs its headers in $PREFIX/lib/libffi-$VERSION/include,
        # instead of $PREFIX/include, so we copy them to the default location.
        execute mkdir -p $INSTALL_FOLDER/include
        execute cp $INSTALL_FOLDER/lib*/libffi-*/include/* \
            $INSTALL_FOLDER/include/
        # On some systems libffi is installed in lib64/ and then cffi is
        # searching for it in lib/ (this affects RHEL 5-7 and SLES 11-12).
        if [ -d $INSTALL_FOLDER/lib64 ]; then
            execute cp $INSTALL_FOLDER/lib64/* $INSTALL_FOLDER/lib/
        fi
    fi
}


select_chevahbs_command $@
