#!/usr/bin/env bash
#
# Chevah Build Script for zlib.

# Import shared code.
. ./functions.sh


chevahbs_configure() {
    # We want static builds only, so that we don't have to mess with LIBPATH.
    CONF_OPTS="--static"
    case $OS in
        hpux*)
            # When building 64bit binaries (as required by libffi),
            # zlib build will fail with aCC -Ae.
            MAKE="gmake"
            CC="/opt/aCC/bin/cc -w"
            unset LDSHARED
            unset CFLAGS
            ;;
    esac
    execute eval $CONF_VARS ./configure --prefix="" $CONF_OPTS
}


chevahbs_compile() {
    execute $MAKE
}


chevahbs_install() {
    install_folder=$1
    execute $MAKE install DESTDIR=$INSTALL_FOLDER
}


select_chevahbs_command $@

