#!/usr/bin/env bash
#
# Chevah Build Script for zlib.

# Import shared code and the Bash checks.
. ./functions.sh


chevahbs_configure() {
    # We want static builds only, so that we don't have to mess with LIBPATH.
    CONF_OPTS="--static"
    execute ./configure --prefix="" $CONF_OPTS
}


chevahbs_compile() {
    execute $MAKE
}


chevahbs_install() {
    install_folder=$1
    execute $MAKE install DESTDIR=$INSTALL_FOLDER
}


select_chevahbs_command $@
