#!/usr/bin/env bash
#
# Chevah Build Script for libxcrypt.

# Import shared code.
. ./functions.sh


chevahbs_configure() {
    CONF_OPTS="--static"
    execute ./configure --prefix="" $CONF_OPTS
}


chevahbs_compile() {
    execute $MAKE
}


chevahbs_install() {
    install_folder=$1
    execute $MAKE install DESTDIR=$INSTALL_FOLDER
}


select_chevahbs_command $@
