#!/usr/bin/env bash
#
# Chevah Build Script for libxcrypt.

# Import shared code.
. ./functions.sh

chevahbs_patch() {
    # On CentOS 5.11, Perl 5.10 is what we have.
    echo "Applying force_perl_510.patch:"
    execute patch -p1 < force_perl_510.patch
}

chevahbs_configure() {
    CONF_OPTS="--enable-static --enable-hashes=glibc"
    execute ./configure --prefix="" $CONF_OPTS
}


chevahbs_compile() {
    execute $MAKE
}


chevahbs_install() {
    install_folder=$1
    execute $MAKE install DESTDIR=$INSTALL_FOLDER
}


select_chevahbs_command $@
