#!/bin/bash
#
# Chevah Build Script for Python.
#
# Import shared code.
. ./functions.sh


chevahbs_configure() {
    CONFIG_ARGS="--disable-shared"

    CONFIGURE_ENVIRONMENT=""

    case $OS in
        "hpux")
            export EXTRA_CFLAGS="-D_REENTRANT"
            export LIBS="-lpthread"
            CONFIG_ARGS="${CONFIG_ARGS} --without-gcc --without-ctypes"
            ;;
        "ubuntu1004")
            # On Ubuntu there are no libXXX.o, but rather linked against the
            # full version number.
            CONFIG_ARGS="${CONFIG_ARGS} \
                --with-bz2-version=1 \
                --with-crypt-version=1 \
                --with-openssl-version=0.9.8 \
                "
            ;;
        "ubuntu1204")
            CONFIG_ARGS="${CONFIG_ARGS} \
                --with-bz2-version=1 \
                --with-crypt-version=1 \
                --with-openssl-version=1.0.0 \
                "
            ;;
        aix*)
            # These files are already created in the Python distribution,
            # but for some strange reason, make tries to recreate them.
            # We just touch them so that make will see them up to date.
            touch Include/Python-ast.h Python/Python-ast.c
            # MAXMEM option with a value greater than 8192.
            CONFIG_ARGS="${CONFIG_ARGS} \
                --without-gcc \
                --with-system-ffi \
                "

            # On AIX we build _ctypes with external libffi, but not from
            # system /usr/lib folder but from a local build folder since
            # we will use the static linking.
            execute mkdir -p build/libffi
            execute cp $INSTALL_FOLDER/tmp/libffi/* build/libffi/
            ;;
        solaris*)
            # In Solaris the default OpenSSL installation lives in /usr/sfw/.
            # Both include options are needed to match both the native Sun
            # Studio compiler and GCC.
            if [ "${ARCH%64}" = "$ARCH" ]; then
                echo "_ssl _ssl.c -I/usr/sfw/include" \
                    "-I/usr/sfw/include/openssl -L/usr/sfw/lib" \
                    " -R/usr/sfw/lib -lssl -lcrypto" >> Modules/Setup.local
            else
                CONFIG_ARGS="${CONFIG_ARGS} CFLAGS=-m64 LDFLAGS=-m64"
                echo "_ssl _ssl.c -I/usr/sfw/include" \
                    "-I/usr/sfw/include/openssl -L/usr/sfw/lib/64" \
                    " -R/usr/sfw/lib/64 -lssl -lcrypto" >> Modules/Setup.local
            fi
            ;;
    esac

    execute ./configure --prefix="" $CONFIG_ARGS

    case $OS in
        "hpux")
            cp Makefile Makefile.orig
            # On HPUX -DNDEBUG is causing troubles.
            sed "s/^OPT=.*-O/OPT= -O/"  Makefile.orig > Makefile
            ;;
    esac

}


chevahbs_compile() {
    execute $MAKE
}


chevahbs_install() {
    install_folder=$1
    execute $MAKE install DESTDIR=$INSTALL_FOLDER
}


select_chevahbs_command $@
