#!/usr/bin/env bash
#
# Chevah Build Script for bzip2.

# Import shared code.
. ./functions.sh

chevahbs_patch() {
    # Patch to support PIC and compilers other than GCC.
    echo "Applying cc_fpic.patch:"
    execute patch -p0 < cc_fpic.patch
    case $OS in
        hpux*)
            # For -W flags, cc throws "error 1914: bad form for `-W' option".
            echo "Applying hpux_disable_wflags.patch:"
            execute patch -p0 < hpux_disable_wflags.patch
            # Workaround for tar erroring out with "symbolic link too long".
            echo "Applying hpux_long_symlinks_workaround.patch:"
            execute patch -p0 < hpux_long_symlinks_workaround.patch
            ;;
    esac
}

chevahbs_configure() {
    # Just a stub, bzip2's build doesn't need this.
    execute true
}


chevahbs_compile() {
    execute $MAKE
}


chevahbs_install() {
    install_folder=$1
    execute $MAKE install PREFIX=$INSTALL_FOLDER
}


select_chevahbs_command $@
