#!/usr/bin/env bash
#
# Chevah Build Script for bzip2.

# Import shared code and the Bash checks.
. ./functions.sh

chevahbs_patch() {
    # Patch to support PIC and compilers other than GCC.
    echo "Applying cc_fpic.patch:"
    execute patch -p0 < cc_fpic.patch
}

chevahbs_configure() {
    # Just a stub, bzip2's build doesn't need this.
    execute true
}


chevahbs_compile() {
    execute $MAKE
}


chevahbs_install() {
    execute $MAKE install PREFIX=${INSTALL_FOLDER}
    # Remove its symlinks because they will be copied as dangling by bcrypt.
    execute find ${INSTALL_FOLDER}/bin/ -type l -name 'bz*' -exec rm {} +
    # Also remove the binaries, because they just inflate the packages.
    execute rm ${INSTALL_FOLDER}/bin/{bunzip,bz}*
}


select_chevahbs_command $@
