#!/bin/bash
#
# Chevah Build Script for SQLite main library.
#
# Import shared code.
. ./functions.sh


chevahbs_configure() {
    execute ./configure --enable-readline=no prefix=""
}


chevahbs_compile() {
    execute make
}


chevahbs_install() {
    execute make install DESTDIR=$INSTALL_FOLDER
}


select_chevahbs_command $@
