#!/usr/bin/env bash
#
# Chevah Build Script for libedit.
#
# Import shared code.
. ./functions.sh

chevahbs_patch() {
    # With libedit, terminal state is not properly restored on some OS'es, eg.
    # after exiting the repl on systems with ncurses 6.0, such as Ubuntu 16.04.
    # Patch from https://trac.macports.org/ticket/48807#comment:141.
    # Upstream bugfix (not recommended): https://gnats.netbsd.org/48957.
    echo "Applying terminal_restore.patch:"
    execute patch -p0 < terminal_restore.patch
}

chevahbs_configure() {
    # We want static builds only, so that we don't have to mess with LIBPATH.
    CONF_OPTS="--disable-shared --enable-static"
    case $OS in
        archlinux)
            LDFLAGS="$LDFLAGS -ltinfo"
            ;;
    esac
    # We touch all files to prevent build aborts with:
    # "WARNING: 'aclocal-1.15' is missing on your system."
    find . -type f -exec touch -r acinclude.m4 {} +
    execute ./configure --prefix="" $CONF_OPTS
}


chevahbs_compile() {
    case $OS in
        solaris*)
            # Path to newer awk.
            PATH="/usr/xpg4/bin:$PATH"
            ;;
    esac
    execute $MAKE
}


chevahbs_install() {
    install_folder=$1
    execute $MAKE install DESTDIR=$INSTALL_FOLDER
}


select_chevahbs_command $@

