#!/usr/bin/env bash
#
# Chevah Build Script for libedit.
#
# Import shared code.
. ./functions.sh


chevahbs_configure() {
    # We want static builds only, so that we don't have to mess with LIBPATH.
    CONF_OPTS="--disable-shared --enable-static"
    touch *
    execute ./configure --prefix="" $CONF_OPTS
}


chevahbs_compile() {
    execute $MAKE
}


chevahbs_install() {
    install_folder=$1
    # We copy the includes and libs manually to a temporary location, and
    # we instruct the compiler to link against our lib by augmenting CPPFLAGS
    # with the include's location and LDFLAGS with the location of the libs.
    local temp_folder=$INSTALL_FOLDER/tmp/libedit/
    execute mkdir -p $temp_folder
    execute cp src/.libs/* $temp_folder
    execute ranlib $temp_folder/libedit.a
    execute chmod +x $temp_folder/libedit.a
    execute cp -r src/*.h src/editline/ $temp_folder
}


select_chevahbs_command $@

