#!/bin/bash
#
# Chevah Build Script for GMP.
#
# Import shared code.
. ./functions.sh

chevahbs_configure() {
    # We want only static build so that we don't have to mess with LIBPATH.
    CONF_OPTS="--disable-shared --enable-static"
    if [ x${ARCH} == x"x64" -a  x${os} != x"solaris" ]; then
        # Fix relocation error for amd64 in Linux. More at:
        # https://www.gentoo.org/proj/en/base/amd64/howtos/index.xml?part=1&chap=3#doc_chap7
        CONF_OPTS="$CONF_OPTS --with-pic"
    fi
    execute ./configure --prefix="" $CONF_OPTS
}


chevahbs_compile() {
    execute $MAKE
    # GMP needs to be checked even after a successful compilation.
    # See its INSTALL file for details.
    execute $MAKE check
}


chevahbs_install() {
    install_folder=$1
    # As with libffi, we copy the files manually to a temporary location
    # and then we copy them from there just in time for the compilation of
    # pycrypto. Which we instruct to use them through augmenting CPPFLAGS
    # with the include's location and LDFLAGS with the location of the libs.
    local temp_folder=$INSTALL_FOLDER/tmp/gmp/
    execute mkdir -p $temp_folder
    execute cp .libs/* $temp_folder
    ranlib $temp_folder/libgmp.a
    execute cp gmp.h $temp_folder
}


select_chevahbs_command $@

