language: python
dist: trusty
sudo: required
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7-dev"
 - "pypy"
 - "pypy3"
env:
 - CFFI=no
 - CFFI=yes
matrix:
 exclude:
 - python: pypy
   env: CFFI=no
 - python: pypy3
   env: CFFI=no
 include:
 - python: 3.4
   env: CFFI=no OLDPY=python3.2
 - python: 3.4
   env: CFFI=yes OLDPY=python3.2
 - os: osx
   language: generic
   install: pip2 install cibuildwheel==0.7.1
   after_success: 
   -  cibuildwheel --output-dir wheelhouse;
      ls wheelhouse;
services:
 - docker
branches:
  except:
  - "/^.*-wip$/"
install:
- travis/travis_install.sh
script:
- travis/travis_script.sh
after_success:
- travis/travis_after_success.sh
deploy:
  provider: s3
  access_key_id: AKIAISG4H2IJZLISXOPQ
  secret_access_key:
    secure: DAuc3n+JLxlBmCLgQuLSXwIRHropTVK/TWj3jD99aB1+Bzy5CpmPtXyR3DGltGF2Bum52xcRM8dLFktinFkMqKF7UKZRGNwEey07Nhen94AGjkLomeEM0SRRjVP6T8RqLBK+buNcoRqiFTNM+JlW5ndY6Wy+kFaan+qk3UNz570=
  bucket: pycryptodome-releases
  local_dir: wheelhouse
  skip_cleanup: true
  acl: public_read
  on:
    condition: -d wheelhouse
    all_branches: true
    repo: Legrandin/pycryptodome
    tags: true
