#!/usr/bin/env bash
#
# Chevah Build Script for OpenSSL.

# Import shared code.
. ./functions.sh


chevahbs_configure() {
    # We want static builds only, so that we don't have to mess with LIBPATH.
    CONF_OPTS="no-shared"
    # OpenSSL's build requires an absolute path for --prefix,
    # so we don't use --prefix="" as in the other chevahbs scripts.
    execute ./config --prefix="$INSTALL_FOLDER" $CONF_OPTS
}


chevahbs_compile() {
    # On AIX, OpenSSL's tests have an ~1/6 chance of passing.
    # Just repeating the tests is not enough, a whole rebuild is needed.
    if [ "${OS%aix*}" = "" ]; then
        for i in $(seq 1 20); do
            echo "OpenSSL build ROUND ${i}..."
            execute $MAKE
            $MAKE test
            tests_error_code=$?
            if [ $tests_error_code -eq 0 ]; then
                echo "OpenSSL tests were SUCCESSFUL in ROUND ${i}."
                break
            else
                execute $MAKE clean
            fi
        done
        if [ $tests_error_code -ne 0 ]; then
            echo "OpenSSL tests failed $i times in a row."
            exit 69
        fi
    else
        execute $MAKE
        execute $MAKE test
    fi
}


chevahbs_install() {
    install_folder=$1
    execute $MAKE install
}


select_chevahbs_command $@
